### ISSUE TITLE
make ubr handle mixed lengths

### ISSUE THREAD

**Issue by krispyflow** [DasLab/ubr#1]
Can UBR handle a library of mixed lengths?

**Comment by rhiju** [comment]
Thanks for the suggestion. 

The `ubr_*.py` and `quick_look_ubr` scripts have been updated to handle mixed sequence lengths: https://github.com/DasLab/ubr/commit/56759509fbb38628c1f096f4517952915003fd48

- Sequences with length shorter than the maximum length will have counts files, reactivities, RDAT, etc. padded with zeros.
- Scripts to estimate `signal_to_noise` and normalization values  have been updated to properly "BLANK_OUT" 5' and 3' regions. 
- Overall statistics for average mutation type (Figs. 6 and 7 from `quick_look_ubr`) may not be handling BLANK_OUT correctly.

Please post additional issues if there are important use cases coming up with mixed sequence lengths. Generally, keeping libraries close to a fixed length is experimentally important to allow for PAGE purification of libraries, but it would be good to know about special experiments with mixed lengths.
